import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Dashboard</Link>
        </li>
        <li>
          <Link to="/accountsdebitexpandone">AccountsdebitexpandOne</Link>
        </li>
        <li>
          <Link to="/grantleaveconfirm">Grantleaveconfirm</Link>
        </li>
        <li>
          <Link to="/accountsdebitexpand">Accountsdebitexpand</Link>
        </li>
        <li>
          <Link to="/accountsdebit">Accountsdebit</Link>
        </li>
        <li>
          <Link to="/grantleave">Grantleave</Link>
        </li>
        <li>
          <Link to="/accountcreditdetails">Accountcreditdetails</Link>
        </li>
        <li>
          <Link to="/accountdebitdetails">AccountDebitdetails</Link>
        </li>
        <li>
          <Link to="/attendanceleavemanagement">Attendanceleavemanagement</Link>
        </li>
        <li>
          <Link to="/attendanceout">Attendanceout</Link>
        </li>
        <li>
          <Link to="/accountscreditexpand">Accountscreditexpand</Link>
        </li>
        <li>
          <Link to="/stock">Stock</Link>
        </li>
        <li>
          <Link to="/attendancein">Attendancein</Link>
        </li>
        <li>
          <Link to="/accountscredit">Accountscredit</Link>
        </li>
        <li>
          <Link to="/rooms">Rooms</Link>
        </li>
        <li>
          <Link to="/attendance">Attendance</Link>
        </li>
        <li>
          <Link to="/accounts">Accounts</Link>
        </li>
        <li>
          <Link to="/maintenance">Maintenance</Link>
        </li>
        <li>
          <Link to="/dashboardaddstudentssetuppaymentlinksuccess">
            Dashboardaddstudentssetuppaymentlinksuccess
          </Link>
        </li>
        <li>
          <Link to="/dashboardaddstudentssetuppayment">
            Dashboardaddstudentssetuppayment
          </Link>
        </li>
        <li>
          <Link to="/dashboardaddstudentsbilling">
            Dashboardaddstudentsbilling
          </Link>
        </li>
        <li>
          <Link to="/dashboardaddstudentspreview">
            Dashboardaddstudentspreview
          </Link>
        </li>
        <li>
          <Link to="/dashboardaddstudentsmeal">Dashboardaddstudentsmeal</Link>
        </li>
        <li>
          <Link to="/dashboardaddstudentsallocation">
            Dashboardaddstudentsallocation
          </Link>
        </li>
        <li>
          <Link to="/dashboardaddstudentsguardians">
            Dashboardaddstudentsguardians
          </Link>
        </li>
        <li>
          <Link to="/dashboardaddstudentsaddress">
            Dashboardaddstudentsaddress
          </Link>
        </li>
        <li>
          <Link to="/dashboardaddstudents">Dashboardaddstudents</Link>
        </li>
        <li>
          <Link to="/dashboardstudents">Dashboardstudents</Link>
        </li>
        <li>
          <Link to="/hostelshostel">Hostelshostel</Link>
        </li>
        <li>
          <Link to="/dashboardaddhostels">Dashboardaddhostels</Link>
        </li>
        <li>
          <Link to="/dashboardaddhostelsconfirmation">
            Dashboardaddhostelsconfirmation
          </Link>
        </li>
        <li>
          <Link to="/hostelsrooms">Hostelsrooms</Link>
        </li>
        <li>
          <Link to="/dashboardaddroomsone">DashboardaddroomsOne</Link>
        </li>
        <li>
          <Link to="/dashboardaddroomsthree">DashboardaddroomsThree</Link>
        </li>
        <li>
          <Link to="/dashboardaddrooms">Dashboardaddrooms</Link>
        </li>
        <li>
          <Link to="/dashboardaddroomsfurniture">
            Dashboardaddroomsfurniture
          </Link>
        </li>
        <li>
          <Link to="/dashboardaddroomstwo">DashboardaddroomsTwo</Link>
        </li>
        <li>
          <Link to="/dashboardaddstudentsduration">
            Dashboardaddstudentsduration
          </Link>
        </li>
        <li>
          <Link to="/viewstudentsouthostel">Viewstudentsouthostel</Link>
        </li>
        <li>
          <Link to="/viewstudentsinhostel">Viewstudentsinhostel</Link>
        </li>
        <li>
          <Link to="/viewstudents">Viewstudents</Link>
        </li>
        <li>
          <Link to="/dashboardadddefaulter">DashboardaddDefaulter</Link>
        </li>
        <li>
          <Link to="/hostelsassigned">Hostelsassigned</Link>
        </li>
        <li>
          <Link to="/hostelassignedmodal">Hostelassignedmodal</Link>
        </li>
        <li>
          <Link to="/removetenant">Removetenant</Link>
        </li>
        <li>
          <Link to="/removetenantcheck">Removetenantcheck</Link>
        </li>
        <li>
          <Link to="/removetenantpaymentnotrecieved">
            Removetenantpaymentnotrecieved
          </Link>
        </li>
        <li>
          <Link to="/removetenantsuccess">Removetenantsuccess</Link>
        </li>
        <li>
          <Link to="/removeteantmoneyrecovery">Removeteantmoneyrecovery</Link>
        </li>
        <li>
          <Link to="/removetenantcheckpaymentlink">
            Removetenantcheckpaymentlink
          </Link>
        </li>
        <li>
          <Link to="/dashboardaddstudentscancellationprompt">
            Dashboardaddstudentscancellationprompt
          </Link>
        </li>
        <li>
          <Link to="/viewstudentsassignedhostelone">
            ViewstudentsassignedhostelOne
          </Link>
        </li>
        <li>
          <Link to="/viewstudentsunassignedhostel">
            Viewstudentsunassignedhostel
          </Link>
        </li>
        <li>
          <Link to="/viewstudentsremovedhostel">Viewstudentsremovedhostel</Link>
        </li>
        <li>
          <Link to="/dashboardadddefaulterconfirm">
            DashboardaddDefaulterconfirm
          </Link>
        </li>
        <li>
          <Link to="/hostelfurnituremodal">Hostelfurnituremodal</Link>
        </li>
        <li>
          <Link to="/hosteladdfurniture">Hosteladdfurniture</Link>
        </li>
        <li>
          <Link to="/hosteladdvendor">Hosteladdvendor</Link>
        </li>
        <li>
          <Link to="/hosteladdfurnituretwo">HosteladdfurnitureTwo</Link>
        </li>
        <li>
          <Link to="/hostelfurniturepayment">Hostelfurniturepayment</Link>
        </li>
        <li>
          <Link to="/hostelfurniturepaymentsuccesfull">
            Hostelfurniturepaymentsuccesfull
          </Link>
        </li>
        <li>
          <Link to="/hostelfurniturepaymentpaylater">
            Hostelfurniturepaymentpaylater
          </Link>
        </li>
        <li>
          <Link to="/hostelsfurniture">Hostelsfurniture</Link>
        </li>
        <li>
          <Link to="/viewstudentsassignedhostel">
            Viewstudentsassignedhostel
          </Link>
        </li>
        <li>
          <Link to="/hostelfurnitureorderviewdetails">
            Hostelfurnitureorderviewdetails
          </Link>
        </li>
        <li>
          <Link to="/hostelfurniturepayamount">Hostelfurniturepayamount</Link>
        </li>
        <li>
          <Link to="/hostelfurniturepayamountconfirm">
            Hostelfurniturepayamountconfirm
          </Link>
        </li>
        <li>
          <Link to="/hostelfurniturereportdamageone">
            HostelfurniturereportdamageOne
          </Link>
        </li>
        <li>
          <Link to="/hosteladdfurnitureselectcategory">
            Hosteladdfurnitureselectcategory
          </Link>
        </li>
        <li>
          <Link to="/hostelfurniturereportdamage">
            Hostelfurniturereportdamage
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
